---
name: metal-stack component release

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1

  container-build:
    uses: metal-stack/actions-common/.github/workflows/container-build.yaml@container-build-action
    secrets: inherit
